# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

# siguiendo el ejemplo de https://docs.github.com/es/actions/using-containerized-services/creating-postgresql-service-containers

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    # container: node:16

    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5        

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: psql -c 'create user test_user password $$test_pass$$;' -U postgres
    - run: psql -c 'create user test_super superuser password $$super_pass$$;' -U postgres
    - run: psql -c 'create database test_db owner test_user;' -U postgres
    - run: chmod -v a+r test/fixtures/many-sep-lines.txt
    - run: chmod -v a+r /home/travis/build/codenautas/pg-promise-strict/test/fixtures/many-sep-lines.txt
    - run: export FILE4TEST=`mktemp`
    - run: cp /home/travis/build/codenautas/pg-promise-strict/test/fixtures/many-sep-lines.txt $FILE4TEST
    - run: chmod -v a+r $FILE4TEST
    - run: ls -cal
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
